name: ForceSpawn
description: $description
version: '${version}'

main: com.carloscapo.forceSpawn.ForceSpawn
paper-plugin-loader: com.carloscapo.forceSpawn.ForceSpawnLoader
api-version: '26.3'
load: POSTWORLD

authors: [ Picuu ]
website: https://github.com/picuu/force-spawn
