name: ForceSpawn
description: $description
version: '${version}'

main: com.carloscapo.forceSpawn.ForceSpawn
api-version: '26.3'
load: POSTWORLD

authors: [ Picuu ]
website: https://github.com/picuu/force-spawn

permissions:
  fspawn.admin:
    description: Allows configuring ForceSpawn
    default: op
